services:

  db:
      image: postgres
      restart: always
      env_file:
        - .env
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - ./db-data/:/var/lib/postgresql/data/
  api:
      env_file:
        - .env
      build:
        context: ./backend
        dockerfile: prod_dockerfile
      ports:
        - ${API_PORT}:5000
      depends_on:
        - db
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api