services:

  db:
      image: postgres
      restart: always
      env_file:
        - .env
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - ./db-data/:/var/lib/postgresql/data/
  api:
      env_file:
        - .env
      build:
        context: ./backend
        dockerfile: prod_dockerfile
      ports:
        - ${API_PORT}:5000
      depends_on:
        - db
  nginx:
    env_file:
      - .env
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt
    depends_on:
      - api
    restart: always
  certbot:
      image: certbot/certbot:latest
      volumes:
       - ./certbot/www/:/var/www/certbot/
       - ./certbot/conf/:/etc/letsencrypt/
      command: certonly --webroot -w /var/www/certbot --force-renewal --email haltermann.kyle@gmail.com -d rulecrafter.net --agree-tos