const articlePage = `
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title>{{articleTitle}}</title>
    <meta name="description" content="Automatically generated by Rulecrafter.net">
    <link rel="stylesheet" type="text/css" href="{{styleURL}}">
    </head>
    <body>
    {{> article-content}}
    {{#if keywords}}
    <h2 class="section-heading" id="keyword-glossary-header">Keywords</h2>
        {{#each keywords}}
            <h4 id="{{id}}" >{{keyword}}</h6>
            <p class="keyword-short-description"><em>{{shortDefinition}}</em></p>
            <p class="keyword-long-description">{{longDefinition}}</p>
        {{/each}}
    {{/if}}
    </body>
</html>`;
export default articlePage;
