const articlePage = `
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title>{{articleTitle}}</title>
    <meta name="description" content="Automatically generated by Rulecrafter.net">
    <link rel="stylesheet" type="text/css" href="{{rootStyleUrl}}">
    <link rel="stylesheet" type="text/css" href="{{styleURL}}">
    </head>
    <body>
    {{> article-content}}
    {{#if keywords}}
    <h2 class="section-heading" id="keyword-glossary-header">Keywords</h2>
        {{#each keywords}}
            {{> keyword-content keyword=this}}
        {{/each}}
    {{/if}}
    </body>
</html>`;
export default articlePage;
