const rulesetPage = `
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title>{{ruleset.rn_name}}</title>
    <meta name="description" content="Automatically generated by Rulecrafter.net">
    <link rel="stylesheet" type="text/css" href="{{rootCssUrl}}">
    <link rel="stylesheet" type="text/css" href="{{articleCssUrl}}">
    <link rel="stylesheet" type="text/css" href="{{rulesetCssUrl}}">
    </head>
    <body>
    <h1 id="ruleset-title">{{ruleset.rn_name}}</h1>
    <h2 class="section-heading">Table of Contents</h2>
    <ol>
        {{~#each ruleset.articles~}}
            <li>{{> toc-entry this}}</li>
        {{~/each~}}
        <li><h4 class="table-of-contents-entry"><a href="#keyword-glossary-header">Keyword Glossary</a></h4></li>
    </ol>

    {{#each articles}}
        {{> article-content article=this}}
    {{/each}}
    {{#if keywords}}
    <h2 class="section-heading" id="keyword-glossary-header">Keywords</h2>
        {{#each keywords}}
            {{> keyword-content keyword=this}}
        {{/each}}
    {{/if}}
    </body>
</html>`;
export default rulesetPage;
